### PR TITLE
Increase project version to v0.1.1

### PR DESCRIPTION
**Pull request by lmh91**

### CODE REVIEW

**Comment by fhagemann** [comment]
What about upgrading also to RadiationDetectorSignals v0.3.0?
(Does LegendDataTypes even depend on anything from RadiationDetectorSignals at all??)

**Comment by lmh91** [comment]
So that people can pin to RadiationDetectorSignals v0.2 for a while if they don't want to upgrade immediately. 
We would directly make a new minor (breaking) release which require RadiationDetectorSignals v0.3.

I would prefer it like that since the last release of this package was not recently.

**Comment by fhagemann** [comment]
Is the RadiationDetectorSignals dependency even needed in this package?

**Comment by lmh91** [comment]
Don't know but does not seems like it. @oschulz should know as he wrote this?

If so, we can just remove it and don't need a second (minor) release after this patch release.

**Comment by oschulz** [comment]
> Don't know but does not seems like it. @oschulz should know as he wrote this?

I think it can be removed.

**Pull request merged**
